# Generated by Django 4.0.3 on 2022-03-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recharge',
            new_name='Googlerecharge',
        ),
    ]
