# Generated by Django 4.0.3 on 2022-03-25 10:49

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_recharge_googlerecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlerecharge',
            name='transid',
            field=models.CharField(default=myapp.models.tns, max_length=15, unique=True),
        ),
    ]
